all: flat_earth spherical_earth
hw3_flat:
	g++ flat_earth.cpp Camera.cpp helper.cpp KeyCommand.cpp Material.cpp Window.cpp -o hw3_flat -std=c++11 -lXi -lGLEW -lGLU -lm -lGL -lm -lpthread -ldl -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lglfw3 -lrt -lm -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp -ljpeg

hw3_sphere:
	g++ spherical_earth.cpp Camera.cpp helper.cpp KeyCommand.cpp Material.cpp Window.cpp -o hw3_sphere -std=c++11 -lXi -lGLEW -lGLU -lm -lGL -lm -lpthread -ldl -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lglfw3 -lrt -lm -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp -ljpeg
